### ISSUE TITLE
Request for Slides

### ISSUE THREAD

**Issue by lightyears1998** [zi-ming/SFIV_with_DQN#1]
Hi, there. @zi-ming 

I'd like to say that you have made a charming presentation during our attending AI course last Thursday! I have been studying your code for a bit since yesterday, and there are a few points I want to review in your slides. Would you kindly upload your PowerPoint files to the repo?

Thanks in advance!

**Comment by zi-ming** [comment]
> @lightyears1998 

Thank you very much for your support, I have uploaded the PPT used in the class to the repo, where the code in the PPT may be slightly different from the code on github, but the code logic is the same.

Hope it can help you!
